# Generated by Django 5.1.5 on 2025-01-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('supervisor', models.CharField(max_length=50)),
                ('skills_required', models.TextField(help_text='The skills required for the project.')),
                ('duration', models.PositiveIntegerField(help_text='The duration of the project in months.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the project offer is active or closed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date the offer was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last update date of the offer.')),
            ],
        ),
    ]
