# Generated by Django 5.1.5 on 2025-01-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerapplication',
            name='cv',
        ),
    ]
