# Generated by Django 5.1.5 on 2025-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_offerapplication_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='offerapplication',
            old_name='discription',
            new_name='description',
        ),
    ]
