# Generated by Django 5.1.5 on 2025-01-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_application_delete_createoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
