# Generated by Django 5.1.5 on 2025-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_alter_offer_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='supervisor',
            field=models.CharField(max_length=50),
        ),
    ]
