# Generated by Django 5.1.5 on 2025-01-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_alter_offer_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='supervisor',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
