# Generated by Django 5.1.5 on 2025-01-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
